<?php

return [
	'site' => [
		'name' => 'UGC | Staff Panels',
		'icon' => 'fas fa-users-cog'
	],
	'db' => [
		'host' => 'localhost',
		'user' => 'srcds_source',
		'password' => '',
		'name' => 'srcds_source',
	],
	'games' => [
		[
			'name' => 'Team Fortress 2',
			'icon' => 'fab fa-steam',
			'visible' => true,
			'panels' => [
				[
					'name' => 'Add High Privileges',
					'route' => '/tf2/add-high-privileges',
					'controller' => 'Tf2/AddHighPrivilegeController',
					'method' => 'addHighPrivileges',
					'form_method' => 'processForm',
					'icon' => 'fas fa-plus',
					'access' => 'admin',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Edit Privileges',
					'route' => '/tf2/edit-privileges',
					'controller' => 'Tf2/EditPrivilegeController',
					'method' => 'editPrivileges',
					'icon' => 'fas fa-user-cog',
					'access' => 'admin',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'ASN Bans',
					'route' => '/tf2/asn-bans',
					'controller' => 'Tf2/AsnBanController',
					'method' => 'manageAsn',
					'icon' => 'fas fa-ban',
					'access' => 'admin',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Subnet Bans',
					'route' => '/tf2/subnet-bans',
					'controller' => 'Tf2/SubnetBanController',
					'method' => 'manageCidr',
					'icon' => 'fas fa-ban',
					'access' => 'admin',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Cidr Whitelist',
					'route' => '/tf2/cidr-whitelist',
					'controller' => 'Tf2/CidrWhitelistController',
					'method' => 'manageCidr',
					'icon' => 'fas fa-check-circle',
					'access' => 'admin',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'ASN/Cidr Logs',
					'route' => '/tf2/asn-cidr-logs',
					'controller' => 'Tf2/AsnCidrLogController',
					'method' => 'manageAsnCidr',
					'icon' => 'fas fa-clipboard-list',
					'access' => 'admin',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Add Privileges',
					'route' => '/tf2/add-privileges',
					'controller' => 'Tf2/AddPrivilegeController',
					'method' => 'addPrivileges',
					'form_method' => 'processForm',
					'icon' => 'fas fa-plus',
					'access' => 'smod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Remove Privileges',
					'route' => '/tf2/remove-privileges',
					'controller' => 'Tf2/RemovePrivilegeController',
					'method' => 'removePrivileges',
					'form_method' => 'processForm',
					'icon' => 'fas fa-trash-alt',
					'access' => 'smod',
					'active' => false,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Manage Privileges',
					'route' => '/tf2/view-privileges',
					'controller' => 'Tf2/ViewPrivilegeController',
					'method' => 'viewPrivileges',
					'icon' => 'fas fa-eye',
					'access' => 'smod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Manage Warnings',
					'route' => '/tf2/manage-warnings',
					'controller' => 'Tf2/ManageWarningController',
					'method' => 'manageWarnings',
					'icon' => 'fa fa-exclamation-triangle',
					'access' => 'smod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Super Spray Handler',
					'route' => '/tf2/super-spray-handler',
					'controller' => 'Tf2/SuperSprayController',
					'method' => 'manageSprays',
					'icon' => 'fas fa-paint-brush',
					'access' => 'smod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Admin Logs',
					'route' => '/tf2/admin-logs',
					'controller' => 'Tf2/AdminLogController',
					'method' => 'manageLogs',
					'icon' => 'fas fa-book',
					'access' => 'mod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Vote Logs',
					'route' => '/tf2/vote-logs',
					'controller' => 'Tf2/VoteLogController',
					'method' => 'manageVotes',
					'icon' => 'fas fa-book',
					'access' => 'mod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'CallAdmin Block',
					'route' => '/tf2/calladmin-block',
					'controller' => 'Tf2/CallAdminBlockController',
					'method' => 'manageCalls',
					'icon' => 'fas fa-phone',
					'access' => 'mod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
				[
					'name' => 'Player Analytics',
					'route' => '/player-analytics',
					'controller' => '',
					'method' => '',
					'icon' => 'fa fa-line-chart',
					'access' => 'mod',
					'active' => true,
					'db' => [
						'host' => 'localhost',
						'user' => 'srcds_source',
						'password' => '',
						'name' => 'srcds_source',
					],
				],
			]
		],
		[
			'name' => 'Game 2',
			'icon' => '',
			'visible' => false,
			'panels' => [
				[
					'name' => 'Panel 1',
					'route' => '/test/panel1',
					'controller' => 'Panel1Controller',
					'method' => 'manageX',
					'icon' => '',
					'access' => 'mod',
					'active' => false
				],
				[
					'name' => 'Panel 2',
					'route' => '/test/panel2',
					'controller' => 'Panel2Controller',
					'method' => 'manageX',
					'icon' => '',
					'access' => 'mod',
					'active' => false
				]
			]
		]
	]
];
